### ISSUE TITLE
Create smooth transition to postgres

### ISSUE THREAD

**Issue by seancdavis** [seancdavis/sapwood-classic#170]

**Comment by seancdavis** [comment]
It's fairly straightforward, but some manual process. Mostly it relies on the [`yaml_db` gem](https://github.com/yamldb/yaml_db) (which is awesome). Here are the steps as I see it:
1. Install postgresql (if necessary)
2. `bundle install` (part of routine update)
3. Dump the existing data (`bundle exec rake db:data:dump`)
4. Swap out the `database.yml` config
5. Create and migrate the database (`bundle exec rake db:create; bundle exec rake db:migrate`)
6. Import the data (`bundle exec rake db:data:load`)

The postgresql database config is simple:

``` yaml
production:
  adapter: postgresql
  database: [db_name]
  username: [db_user]
  password: [db_pass]
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
```

**Comment by seancdavis** [comment]
In addition to above, on the production server, you want to install postgres:

``` text
$ sudo apt-get -y install postgresql libpq-dev postgresql-contrib
```

Log in to psql and then create the role.

``` text
$ sudo -u postgres psql

postgres=# CREATE ROLE [db_user] LOGIN CREATEDB PASSWORD '[db_pass]';
```

Then move on to the steps above.

You will also need a hard restart when you finally restart the server:

``` text
$ sudo service unicorn_sapwood stop
$ sudo service unicorn_sapwood start
```

**Comment by seancdavis** [comment]
And for development, we'll need to open up postgres for remote connections.

In `/etc/postgresql/9.3/main/pg_hba.conf`, add this to the bottom:

``` text
host    all             all             0.0.0.0/0               trust
```

In `/etc/postgresql/9.3/main/postgresql.conf`, change this:

``` text
listen_addresses = 'localhost'          # what IP address(es) to listen on;
```

to this:

``` text
listen_addresses = '*'          # what IP address(es) to listen on;
```

Then enable `5432` port if you're using `ufw`:

``` text
$ sudo ufw allow 5432
```

Restart postgres:

``` text
$ sudo service postgresql restart
```

And in your development `config/database.yml`, the config probably looks something like this:

``` yaml
development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: [prod_ip]
  port: 5432
  username: [db_user]
  password: [db_pass]
  database: [db_name]
```
