### ISSUE TITLE
No access to builder in development

### ISSUE THREAD

**Issue by seancdavis** [seancdavis/sapwood-classic#73]
Set it up to use the production (remote) database in development.

**Comment by seancdavis** [comment]
This is mostly focused around pointing the development instance to production. This means we need to:
- configure the production server to accept remote connections
- adjust development database config

**Production Server**

Login to mysql as `root` (or equivalent user):

``` text
$ mysql -u root -p
```

Then, grant the production database user appropriate permissions.

``` text
mysql> grant all on [db_name].* to [db_user]@'[your_dev_public_ip]' identified by '[db_pass]';
```

Where you replace all the `[]` values.

Next, note the port on which mysql is connecting and the path to the socket file. Both of these values should be listed in `/etc/mysql/my.cnf`.

If you are using a firewall, be sure the port mysql is using is open.

**Development Config**

Back in development, you'll want to add a `host` matching the ip address of the production server:

``` yaml
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: [taproot_production_ip_address]
  username: [db_user]
  password: [db_pass]
  port: [mysql_port]
  socket: [path_to_socket]

development:
  <<: *default
  database: taproot_production
```
